# Generated by Django 3.0.5 on 2020-04-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='total_pictures',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
