# Generated by Django 2.2.5 on 2020-04-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_plant_total_pictures'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='active_pi',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
